pub(crate) use crate::certificate_completion_load_current_v2::current;
pub(crate) use crate::certificate_completion_load_original_v2::original;

pub(crate) struct CompletionReservation {
    pub(crate) authorization_jti: String,
    pub(crate) action: String,
    pub(crate) related_authorization_jti: Option<String>,
    pub(crate) operation_id: String,
    pub(crate) lease_digest_sha256: String,
    pub(crate) command_digest_sha256: String,
    pub(crate) target_resource_id: String,
    pub(crate) expected_resource_version: u64,
    pub(crate) previous_fence: u64,
    pub(crate) current_fence: u64,
    pub(crate) previous_lifecycle_epoch: u64,
    pub(crate) lifecycle_epoch: u64,
    pub(crate) security_domain: String,
    pub(crate) deployment_id: String,
    pub(crate) provider: String,
    pub(crate) service_id: String,
    pub(crate) workload: String,
    pub(crate) pairwise_subject: String,
    pub(crate) profile: String,
    pub(crate) command_json: String,
}

pub(crate) struct OriginalUnknown {
    pub(crate) authorization_jti: String,
    pub(crate) operation_id: String,
    pub(crate) action: String,
    pub(crate) pa_reservation_id: String,
    pub(crate) lease_digest_sha256: String,
    pub(crate) command_digest_sha256: String,
    pub(crate) unknown_evidence_digest_sha256: String,
    pub(crate) previous_fence: u64,
    pub(crate) current_fence: u64,
    pub(crate) previous_lifecycle_epoch: u64,
    pub(crate) lifecycle_epoch: u64,
    pub(crate) security_domain: String,
    pub(crate) deployment_id: String,
    pub(crate) provider: String,
    pub(crate) target_resource_id: String,
    pub(crate) expected_resource_version: u64,
    pub(crate) service_id: String,
    pub(crate) workload: String,
    pub(crate) pairwise_subject: String,
    pub(crate) profile: String,
    pub(crate) command_json: String,
}
